# Generated by Django 6.1 on 2026-08-10 18:26

import auth_client.fields
import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='token hash')),
                ('user_id', models.CharField(db_index=True, max_length=26, verbose_name='user id')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('access_token', auth_client.fields.EncryptedTextField(verbose_name='access token')),
                ('refresh_token', auth_client.fields.EncryptedTextField(verbose_name='refresh token')),
                ('access_expires_at', models.DateTimeField(verbose_name='access token expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'app session',
                'verbose_name_plural': 'app sessions',
            },
        ),
    ]
