# Generated by Django 6.1 on 2026-09-09 14:26

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='token hash')),
                ('last_four', models.CharField(max_length=4, verbose_name='last four')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'personal access token',
                'verbose_name_plural': 'personal access tokens',
            },
        ),
    ]
