# Generated by Django 6.1 on 2026-08-19 21:43

import agents.constants
import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('provider', models.CharField(max_length=32, verbose_name='provider')),
                ('source', models.CharField(max_length=64, verbose_name='source')),
                ('model', models.CharField(max_length=256, verbose_name='model')),
                ('prompt', models.TextField(verbose_name='prompt')),
                ('tools', models.JSONField(default=dict, help_text='{web_search, find_contacts} booleans', verbose_name='tools')),
                ('outputs', models.JSONField(default=list, help_text='[{key, label, type, description}], at least one', verbose_name='outputs')),
                ('ephemeral', models.BooleanField(default=False, verbose_name='ephemeral')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'indexes': [models.Index(fields=['account_id', 'id'], name='agent_account_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentTestRun',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('status', models.CharField(default='pending', max_length=16, verbose_name='status')),
                ('error', models.CharField(blank=True, default='', max_length=256, verbose_name='error')),
                ('result', models.JSONField(default=dict, help_text='{cells, evidence, searches} when complete', verbose_name='result')),
            ],
            options={
                'verbose_name': 'agent test run',
                'verbose_name_plural': 'agent test runs',
                'indexes': [models.Index(fields=['account_id', 'id'], name='agenttestrun_account_idx')],
            },
        ),
    ]
