# Generated by Django 6.1 on 2026-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.CheckConstraint(condition=models.Q(('outputs__0__isnull', False)), name='agent_outputs_min1'),
        ),
    ]
