# Generated by Django 6.1 on 2026-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_agent_outputs_min1'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttestrun',
            name='polled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='polled at'),
        ),
    ]
