# Generated by Django 6.1 on 2026-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agenttestrun_polled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttestrun',
            name='config_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='config fingerprint'),
        ),
        migrations.AddField(
            model_name='agenttestrun',
            name='row_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='row id'),
        ),
    ]
