# Generated by Django 6.1 on 2026-09-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agenttestrun_config_fingerprint_agenttestrun_row_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agenttestrun',
            name='agenttestrun_account_idx',
        ),
        migrations.DeleteModel(
            name='AgentTestRun',
        ),
    ]
