// Generated by packages/schema/scripts/generate.mjs from the shared
// contract (packages/openbower-schema/schema.json). Do not edit by hand.

import { z } from "zod";

export const AgentOutputSchema = z.object({ "description": z.string().max(256).default(""), "key": z.string().max(40).describe("Present always; BLANK allowed on requests (the server derives it from the label) and always populated on responses (required, no default: a response omitting it must fail the parse, never invent an empty string)."), "label": z.string().max(80).describe("Non-blank on the wire (the server refuses blank labels at the request boundary); the builder's local draft may hold blank rows, client-side only."), "type": z.enum(["text","number","currency","date","url","email"]).describe("Sheet display type; drives rendering only.") }).describe("One declared output: a named, described field the model must\nfill (the description rides into the instruction), landing as one\ncell per row.");
export type AgentOutput = z.infer<typeof AgentOutputSchema>;

export const AgentToolsSchema = z.object({ "find_contacts": z.boolean().default(false), "web_search": z.boolean().default(false) }).describe("The tool REGISTRY, one typed field per tool: the wire itself\ncarries the key set, so the web derives its tool list from this\nshape instead of hand-retyping it. Unknown keys are TOLERATED\n(dropped) here because this model validates on every read, and a\nserver that adds a tool must not fail stored rows or a browser\nholding the old bundle; the REQUEST leg's serializer is where\nunknown keys refuse, which is what keeps the set closed on the\nway in.");
export type AgentTools = z.infer<typeof AgentToolsSchema>;

export const AiColumnSchema = z.object({ "current_fill_id": z.string().describe("The fill run that speaks for this column, stored here when it opens and served back as ColumnFillSummary.current_fill_id: the tracker follows THIS run, never the newest by time; \"\" when the column has never run.").default(""), "key": z.string().max(40).describe("Stable snake_case key; row data dicts key on it."), "kind": z.literal("ai").default("ai"), "label": z.string().max(80).describe("Display label, as the user (or the CSV header) wrote it."), "node_id": z.string().describe("The node that fills this column (an agent bound to this sheet)."), "type": z.enum(["text","number","currency","date","url","email"]).describe("Sheet display type; drives rendering only.") }).describe("A column an agent fills. The column binds to the NODE that fills\nit; the agent, and its ephemeral-vs-roster custody, hangs off the\nnode, so editing what fills a column goes through the column,\nnever this id.");
export type AiColumn = z.infer<typeof AiColumnSchema>;

export const AuthUserSchema = z.object({ "account_id": z.string().describe("The user's primary account ULID."), "email": z.string().describe("The user's email address."), "id": z.string().describe("The user's cloud-issued ULID.") }).describe("The authenticated user the app's /v1/auth/me returns (and the identity\nthe IdP resolves). Char-pointer ULIDs, so plain strings on the wire.");
export type AuthUser = z.infer<typeof AuthUserSchema>;

export const CatalogModelSchema = z.object({ "model": z.string(), "provider": z.enum(["openai_compatible","anthropic_compatible"]), "source": z.string() }).describe("One runnable model on this deploy.");
export type CatalogModel = z.infer<typeof CatalogModelSchema>;

export const CellAssessmentSchema = z.object({ "confidence": z.number().default(0), "dropped": z.string().default(""), "reason": z.string().default("") }).describe("One answered output's judgement, INCLUDING the ones the floor\ndiscarded: what the model staked on the answer, the account it\ngave of the evidence, and the value the floor dropped (\"\" when\nthe answer landed). A typed wire shape, not a bare dict: the\nbench renders these fields, and z.any() is a contract that\npromises nothing.");
export type CellAssessment = z.infer<typeof CellAssessmentSchema>;

export const CellStateWireSchema = z.object({ "state": z.enum(["pending","filled","no_evidence","no_answer","unverified","unparseable","type_mismatch","model_error","transient","tool_not_configured","tool_unavailable"]), "tools": z.record(z.string(), z.string()).default({}) }).describe("One AI cell's state and the tool statuses of the run that wrote\nit: `tools` is tool -> status code (a base ToolStatus code or the\ntool's own; \"open\" for a tool that served), empty for a pending\ncell or a run before tools reported statuses. The client resolves\ncopy by (tool, code) and tolerates a code it has not heard of.");
export type CellStateWire = z.infer<typeof CellStateWireSchema>;

export const ColumnPromptWireSchema = z.object({ "model": z.string(), "prompt": z.string(), "source": z.string() }).describe("The column's CURRENT fill config as the server holds it (GET),\nand the echo after a column-scoped edit (PATCH\n/lists/{id}/columns/{key}/prompt). A fill reads its agent live, so\nan edit reaches a running fill's next row; surfaces peeking at\n\"what fills this column\" read HERE.");
export type ColumnPromptWire = z.infer<typeof ColumnPromptWireSchema>;

export const CompanySchema = z.object({ "country": z.string().describe("Country; empty when unknown."), "domain": z.string().describe("Canonical lowercased bare domain."), "founded_year": z.union([z.number().int(), z.null()]).describe("Founding year when known.").default(null), "id": z.string().describe("The company's ULID in the universe."), "industry": z.string().describe("Industry label; empty when unknown."), "linkedin_url": z.string().describe("LinkedIn company URL; empty when unknown."), "locality": z.string().describe("City/locality; empty when unknown."), "name": z.string().describe("Company display name."), "region": z.string().describe("Region/state; empty when unknown."), "size_band": z.string().describe("Coarse employee band, e.g. 1-10; empty when unknown."), "snapshot_date": z.union([z.string(), z.null()]).describe("ISO date the row's data was current.").default(null), "source": z.string().describe("Provenance of the row, e.g. pdl_free.") }).describe("One company from the central universe (seeded from the free PDL\nCompany Dataset, CC BY 4.0). Char-pointer ULID id.");
export type Company = z.infer<typeof CompanySchema>;

export const FillCountersSchema = z.object({ "attempted": z.number().int(), "blank": z.number().int(), "filled": z.number().int(), "transient": z.number().int() }).describe("Progress, DERIVED from the task rows and cell states at read time\n(never a stored counter): attempted is rows with a terminal outcome\nthis fill; blank counts diagnosed blanks; transient counts rows\ncurrently parked in retry.");
export type FillCounters = z.infer<typeof FillCountersSchema>;

export const FillErrorSchema = z.object({ "code": z.string(), "message": z.string() }).describe("A failed fill's two-tier why: `code` is the machine leg (client\nbranching), `message` is server-authored copy rendered verbatim.");
export type FillError = z.infer<typeof FillErrorSchema>;

export const FillRunWireSchema = z.object({ "agent_id": z.string(), "column_keys": z.array(z.string()).describe("The columns this run owns, frozen at consent."), "confirmed_row_count": z.number().int().describe("The progress denominator: the row count the user consented to when the run opened, settled to the rows the walk actually targeted once `targeted_at` is set (only ever downward: a row the user did not consent to is never targeted). The consent echo is a REQUEST field of the same name; the run covers rows up to it and never past it."), "counters": z.lazy(() => FillCountersSchema), "created_at": z.string(), "error": z.union([z.lazy(() => FillErrorSchema), z.null()]).describe("This run's error, both legs (tier 1: the message renders verbatim); None unless the run FAILED, the same predicate ColumnFillSummary.last_error states.").default(null), "heartbeat_at": z.union([z.string(), z.null()]).describe("The latest state change across this run's tasks (derived); the client judges staleness against ROW_LEASE_STALE_SECONDS off the wire, warning-role only (never presented as failure).").default(null), "id": z.string(), "list_id": z.string(), "started_by": z.string().describe("User id, ATTRIBUTION only; authorization is account membership."), "status": z.enum(["pending","running","complete","failed","cancelled"]), "targeted_at": z.union([z.string(), z.null()]).describe("When the run's target set became whole: the walk that queues its runs has offered every row in the consent range. Null while it is still queuing (seconds after the click); a run cannot complete before it is set.").default(null), "updated_at": z.string() }).describe("The fill run envelope. The POST and cancel ECHOES carry every\nstate (a failed run is an API object with its error, not a 4xx);\nthe fills LIST the sheet re-attaches to carries live runs only\n(see FillRunPage).");
export type FillRunWire = z.infer<typeof FillRunWireSchema>;

export const FolderSummarySchema = z.object({ "created_at": z.string(), "id": z.string(), "label": z.string(), "list_count": z.number().int().describe("Server-side count; consent copy must not trust loaded pages."), "updated_at": z.string() }).describe("A flat, account-scoped bucket for lists (taxonomy, not behavior).");
export type FolderSummary = z.infer<typeof FolderSummarySchema>;

export const FoldersListSchema = z.object({ "items": z.array(z.lazy(() => FolderSummarySchema)) });
export type FoldersList = z.infer<typeof FoldersListSchema>;

export const IngestAcceptedSchema = z.object({ "accepted": z.number().int().describe("Number of rows accepted."), "event_id": z.string().describe("The push's idempotency key (caller-supplied, else a minted ULID).") }).describe("The webhook accept receipt. Rows are accepted for asynchronous\nappend, not applied on the response; `event_id` correlates them.");
export type IngestAccepted = z.infer<typeof IngestAcceptedSchema>;

export const ListRowWireSchema = z.object({ "data": z.record(z.string(), z.string()).describe("Cell values keyed by column key.").default({}), "id": z.string(), "states": z.record(z.string(), z.lazy(() => CellStateWireSchema)).describe("AI cell states keyed by column key: every cell without a value, plus filled cells whose run had a degraded tool. Slim on absences by contract, so a long-filled sheet carries almost nothing here. A value in `data` with no entry here IS filled and clean, and never-attempted is likewise an absence.").default({}), "webhooks": z.record(z.string(), z.enum(["waiting","sent","failed"])).describe("Send webhook cell words keyed by the webhook column's key, off the row's newest run for that column. Absent for a row that has never been due for the column.").default({}) }).describe("A row in SHEET ORDER: the page's array order is the order, and a\nrow number is whatever the renderer counts. Nothing about order\nrides the row itself (the server keeps a rank a move rewrites on\none row; a client never needs it).");
export type ListRowWire = z.infer<typeof ListRowWireSchema>;

export const ListRowsPageSchema = z.object({ "items": z.array(z.lazy(() => ListRowWireSchema)), "next_cursor": z.union([z.string(), z.null()]).describe("An opaque cursor for the next page when more rows exist: hand it back as ?after= verbatim (it carries what the server needs to continue; nothing about it is for the client to read).").default(null) });
export type ListRowsPage = z.infer<typeof ListRowsPageSchema>;

export const LookalikeGroupSchema = z.object({ "elbow_rank": z.union([z.number().int(), z.null()]).describe("This group's own boundary: the knee of ITS score decay (null when too short/flat).").default(null), "label": z.string().describe("Human label; empty for the single homogeneous group.").default(""), "seed_domains": z.array(z.string()).default([]), "size": z.number().int().describe("Results this group contributed to the run.").default(0) }).describe("One seed group of a run: heterogeneous cohorts split into distinct\ngroups, each searched by its own centroid and labeled.");
export type LookalikeGroup = z.infer<typeof LookalikeGroupSchema>;

export const LookalikeItemSchema = z.object({ "company": z.lazy(() => CompanySchema), "description": z.string().describe("Site-derived blurb (homepage meta description or title); empty until the domain has a fetched snippet.").default(""), "group": z.string().describe("Label of the seed group that surfaced this candidate; empty for single-group runs.").default(""), "rank": z.number().int().describe("1-based rank in this result set."), "score": z.number().describe("Similarity score in [0, 1].") }).describe("One ranked look-alike candidate.");
export type LookalikeItem = z.infer<typeof LookalikeItemSchema>;

export const LookalikeListResponseSchema = z.object({ "detail": z.union([z.string(), z.null()]).describe("Failure detail when status is failed.").default(null), "engine": z.string().describe("Which engine ranked these, e.g. embedding_v1."), "groups": z.array(z.lazy(() => LookalikeGroupSchema)).describe("The run's seed-group breakdown; single unlabeled entry for homogeneous cohorts.").default([]), "items": z.array(z.lazy(() => LookalikeItemSchema)), "next_cursor": z.union([z.string(), z.null()]).describe("Opaque cursor for the next page.").default(null), "outlier_domains": z.array(z.string()).describe("Seeds set aside by clustering as misfits (excluded from generation, shown to the user).").default([]), "result_count": z.union([z.number().int(), z.null()]).describe("TOTAL results in the completed run (the full lead-list size, independent of page size).").default(null), "run_id": z.union([z.string(), z.null()]).describe("The run to poll; null only when no run exists (e.g. an empty cohort).").default(null), "status": z.enum(["pending","running","complete","failed","canceled"]).describe("Run lifecycle. Terminal: complete | failed | canceled; keep polling: pending | running.").default("complete"), "unresolved_domains": z.array(z.string()).describe("Inline seed domains that are not in the universe.").default([]) }).describe("The look-alike envelope (data service and app proxy alike), for both\nthe query POST and the run-status poll.\n\n`status` drives the async lifecycle: \"complete\" carries the page in\n`items`; \"pending\"/\"running\" mean poll the run (HTTP 202, empty items);\n\"failed\" carries `detail`; \"canceled\" is terminal by request (a fresh\nquery revives the run). The engine computes in a worker, so a cold\ncohort answers pending first and is polled by `run_id`; a cached cohort\nanswers complete inline.");
export type LookalikeListResponse = z.infer<typeof LookalikeListResponseSchema>;

export const PlainColumnSchema = z.object({ "key": z.string().max(40).describe("Stable snake_case key; row data dicts key on it."), "kind": z.literal("plain").default("plain"), "label": z.string().max(80).describe("Display label, as the user (or the CSV header) wrote it."), "type": z.enum(["text","number","currency","date","url","email"]).describe("Sheet display type; drives rendering only.") }).describe("A column the user or an import fills by hand.");
export type PlainColumn = z.infer<typeof PlainColumnSchema>;

export const RowsAddedSchema = z.object({ "added": z.number().int(), "row_count": z.number().int() }).describe("The manual-append receipt.");
export type RowsAdded = z.infer<typeof RowsAddedSchema>;

export const SearchToolCallSchema = z.object({ "attempts": z.number().int(), "discarded": z.number().int(), "hits": z.number().int(), "kind": z.literal("search").default("search"), "provider": z.string(), "query": z.string(), "status": z.string(), "tool": z.string() }).describe("One search-tool call's record: `status` is what the provider\nsaid (open, and hits, possibly zero, is the honest answer; any\nother code is the tool's own failure code saying why there are\nnone), `provider` which provider served it, `attempts` how many\ntries the seam made for this one query (a rate limit is retried,\nsame query, before it counts), and `tool` which tool called, so a\nreader can tell whose call refused. `hits` counts what the tool\nKEPT; `discarded` counts served hits the tool dropped as off-scope\n(an engine that runs dry on a demanded site: relaxes the query and\nserves off-site pages dressed as answers), so a thin answer shows\nwhether the provider ran dry or ran off. Every field REQUIRED: the\none writer sets them all, and a stored record is the same shape as\na served one.");
export type SearchToolCall = z.infer<typeof SearchToolCallSchema>;

export const WebhookColumnSchema = z.object({ "key": z.string().max(40).describe("Stable snake_case key; row data dicts key on it."), "kind": z.literal("webhook").default("webhook"), "label": z.string().max(80).describe("Display label, as the user (or the CSV header) wrote it."), "node_id": z.string().describe("The webhook node this column is; its config and the wait node's hang off the path."), "type": z.enum(["text","number","currency","date","url","email"]).describe("Sheet display type; drives rendering only.") }).describe("A Send webhook column. It IS the second node of its own path\n(the wait node before it names the paths it waits on); the\ncolumn holds no row data, its cells show delivery state.");
export type WebhookColumn = z.infer<typeof WebhookColumnSchema>;

export const WebhookColumnConfigWireSchema = z.object({ "destination_id": z.string(), "destination_label": z.string().describe("The destination's label at read time, for display; the id is the link."), "enabled": z.boolean().describe("False pauses sending; due rows wait until it is resumed.").default(true), "interval_seconds": z.number().int().gt(0).describe("Seconds between sends of due rows: any positive integer; WEBHOOK_CADENCE_SECONDS are the offered presets."), "node_id": z.string().describe("The webhook node the column is; the drawer's test send scopes to it."), "payload_keys": z.array(z.string()).describe("The columns whose values ride in each sent item, in sheet order; a waited-on column rides only if named here too. Never empty, never a webhook column."), "wait_keys": z.array(z.string()).describe("The AI columns a row must complete before it is due, in sheet order. Derived back from the paths the wait node names, so waiting on one output of an agent lists every column that agent fills.") }).describe("A Send webhook column as configured, served by GET and echoed by\nPATCH on /lists/{id}/columns/{key}/webhook: what it waits for, where\nit sends, what rides, how often, and whether it is running.");
export type WebhookColumnConfigWire = z.infer<typeof WebhookColumnConfigWireSchema>;

export const WebhookDeliveryWireSchema = z.object({ "created_at": z.string(), "destination_id": z.string(), "duration_ms": z.number().int().default(0), "error": z.string().describe("What went wrong, in the user's words; empty on ok.").default(""), "http_status": z.union([z.number().int(), z.null()]).describe("The receiver's status code; null when no answer came.").default(null), "id": z.string(), "response_excerpt": z.string().max(1024).describe("The head of the receiver's answer, kept only when it was not a 2xx.").default(""), "status": z.enum(["ok","transient","rejected","blocked"]), "test": z.boolean().default(false), "type": z.enum(["ping","digest"]) }).describe("One attempt to POST to a destination, whatever it answered. `id`\nis the `webhook-id` header that request carried; `type` and `test`\nare the envelope's own, recorded on our side.");
export type WebhookDeliveryWire = z.infer<typeof WebhookDeliveryWireSchema>;

export const WebhookDestinationWireSchema = z.object({ "column_count": z.union([z.number().int(), z.null()]).describe("How many Send webhook columns send here: delete is refused while any do. Carried by the single-destination reads (detail, create, patch, rotate) and null on the roster, which does not pay for it.").default(null), "created_at": z.string(), "enabled": z.boolean().default(true), "header_names": z.array(z.string()).default([]), "id": z.string(), "label": z.string().max(128), "last_delivery": z.union([z.lazy(() => WebhookDeliveryWireSchema), z.null()]).describe("The newest delivery on record, the destination's health; null before any.").default(null), "rotated_at": z.union([z.string(), z.null()]).describe("When the signing secret was last rotated; the previous secret keeps signing for the grace window after it.").default(null), "url": z.string().max(2048) }).describe("A place deliveries go. Header VALUES and the signing secret never\nride here; `header_names` is all the roster shows.");
export type WebhookDestinationWire = z.infer<typeof WebhookDestinationWireSchema>;

export const WebhookDestinationsListSchema = z.object({ "items": z.array(z.lazy(() => WebhookDestinationWireSchema)) });
export type WebhookDestinationsList = z.infer<typeof WebhookDestinationsListSchema>;

export const WebhookDigestItemSchema = z.object({ "cells": z.record(z.string(), z.string()).describe("The payload columns only, by key (the user chooses what leaves the instance), so a waited-on key may appear in `states` and not here."), "completed_at": z.union([z.string(), z.null()]).describe("When the last waited-on column settled. Null only on a test send of a row that has not completed; a real digest never sends null.").default(null), "event_id": z.string().describe("An opaque, fixed-width id for this row completion, the same on every redelivery of it; the same row completing again ships under a new one. Receivers dedup on it and never parse it."), "row_id": z.string(), "states": z.record(z.string(), z.enum(["pending","filled","no_evidence","no_answer","unverified","unparseable","type_mismatch","model_error","transient","tool_not_configured","tool_unavailable"])).describe("The waited-on columns' stored cell states, by key; a column not yet attempted is absent. Never `pending`: a digest reads stored truth, and a row still being worked on is not complete.") }).describe("One completed row of a digest.");
export type WebhookDigestItem = z.infer<typeof WebhookDigestItemSchema>;

export const WebhookPingDataSchema = z.object({ "destination_id": z.string(), "label": z.string(), "type": z.literal("ping").default("ping") }).describe("A destination's Test button: nothing from a sheet, just proof\nthat a signed delivery reaches the receiver.");
export type WebhookPingData = z.infer<typeof WebhookPingDataSchema>;

export const WebhookSheetRefSchema = z.object({ "id": z.string(), "label": z.string() });
export type WebhookSheetRef = z.infer<typeof WebhookSheetRefSchema>;

export const AgentCatalogSchema = z.object({ "models": z.array(z.lazy(() => CatalogModelSchema)), "search_provider": z.union([z.enum(["duckduckgo","serper"]), z.null()]).describe("The vendor serving web search on this deployment, only while it is READY to serve (registered, wired, credentialed); null otherwise, so client copy never names a vendor whose searches cannot run. Client copy composes it: a rate-limited cell names the metered door only where it is a remedy, never to someone already on it."), "support_followup": z.string().describe("The deployment's needs-attention follow-up, profile-owned server-side (check the logs locally; the operator's support channel hosted). Client copy composes it instead of hedging about an operator it cannot identify."), "tools": z.record(z.string(), z.string()).describe("Each tool's availability BEFORE a run, keyed by registered tool name (web_search, find_contacts): 'open' gates the toggle on; any other code is the reason it is off (today only 'not_configured' can appear here; the run-time codes ride the cells)."), "truncated": z.boolean().describe("True when the catalog cap cut the list: an address past the cap may still RUN (model_for validates against the full roster), it just is not shown.") }).describe("What THIS deploy can run; `tools` gates the toggles.");
export type AgentCatalog = z.infer<typeof AgentCatalogSchema>;

export const AgentConfigSchema = z.object({ "model": z.string(), "outputs": z.array(z.lazy(() => AgentOutputSchema)).min(1).max(8), "prompt": z.string().max(262144), "provider": z.enum(["openai_compatible","anthropic_compatible"]), "source": z.string().describe("Which server of that spec (the env-named source)."), "tools": z.lazy(() => AgentToolsSchema) }).describe("The runtime's interchange unit, shared by both custodies (a\nsaved agent, a column's quick prompt) and the test bench.");
export type AgentConfig = z.infer<typeof AgentConfigSchema>;

export const AgentListItemSchema = z.object({ "created_at": z.string(), "id": z.string(), "label": z.string().max(128), "model": z.string(), "tools": z.lazy(() => AgentToolsSchema), "updated_at": z.string() }).describe("One list row: the index ships what the table renders, never\neach agent's whole config (a full list of maxed prompts would be\nmegabytes to draw four columns; the edit page fetches its agent by\nid).");
export type AgentListItem = z.infer<typeof AgentListItemSchema>;

export const AgentSummarySchema = z.object({ "config": z.lazy(() => AgentConfigSchema), "created_at": z.string(), "ephemeral": z.boolean().describe("True for a column-owned quick-prompt agent: hidden from the roster, excluded from MAX_AGENTS, deleted with its column."), "id": z.string(), "label": z.string().max(128), "updated_at": z.string() }).describe("A stored agent (one custody of a config).");
export type AgentSummary = z.infer<typeof AgentSummarySchema>;

export const AgentsListSchema = z.object({ "items": z.array(z.lazy(() => AgentListItemSchema)) });
export type AgentsList = z.infer<typeof AgentsListSchema>;

export const CellRunResultSchema = z.object({ "assessments": z.record(z.string(), z.lazy(() => CellAssessmentSchema)).default({}), "blamed_tool": z.string().default(""), "cells": z.record(z.string(), z.string()).default({}), "declined_cause": z.string().default(""), "evidence": z.array(z.string()).default([]), "tool_calls": z.array(z.lazy(() => SearchToolCallSchema)).default([]), "tools": z.record(z.string(), z.string()).default({}) }).describe("What ONE row's run produced, stored verbatim on the task that\nran it: the cells it would write ({} = nothing, honestly), the\nevidence the model saw, each tool call's diagnosis, and the causes\nbehind any blank.\n\nONE shape for both landings. A sheet row's answers land in its\ncolumns; a bench run lands on itself; both store this record, so a\nreader that had to ask which landing produced it would be reading\ntwo contracts through one field. The bench reads it VERBATIM off\nthe run wire (NodeRunWire carries it whole), so there is no second\nprojection to drift.\n\nWhat LANDED is the sheet row plus its cell states; the difference\nbetween the two is the audit story (an answer write-if-blank\nrefused, a value the confidence floor dropped, a shape the column\nwould not take), which is why this is stored whole rather than\nreduced to what survived.");
export type CellRunResult = z.infer<typeof CellRunResultSchema>;

export const ColumnFillSummarySchema = z.object({ "attempted": z.number().int().describe("Cells this column's fills have RESOLVED: filled plus diagnosed blanks. A targeted cell ends in exactly one of those two places, so their sum is what the column was asked to do. It is the honest denominator for filled; the sheet's row count is a different question."), "column_key": z.string(), "current_fill_id": z.string().describe("The run the column currently names (AiColumn.current_fill_id, its stored pointer), never the newest by time; \"\" when the column has never run."), "current_status": z.union([z.enum(["pending","running","complete","failed","cancelled"]), z.literal("")]).describe("The status of the run current_fill_id names; \"\" when the column has never run. The page's runs list is LIVE runs only, so this is where a terminal story lands."), "filled": z.number().int().describe("Cells in this column that hold a value."), "last_error": z.union([z.lazy(() => FillErrorSchema), z.null()]).describe("The newest run's error, both legs (tier 1: the message renders verbatim); None unless that run FAILED, so a newer clean run clears it and a stopped run carries none.") }).describe("Per-column coverage, computed server-side so the client renders\ninstead of reconstructing (a client sum over one PAGE of fills\nsilently undercounts the moment history outgrows the page).\n\nDeliberately NOT carrying how many rows a refill would target: that\nis planning-grade math on a four-second progress poll. It is asked\nonce, on the consent path, where it has to be exact anyway.");
export type ColumnFillSummary = z.infer<typeof ColumnFillSummarySchema>;

export const FillRunPageSchema = z.object({ "columns": z.array(z.lazy(() => ColumnFillSummarySchema)).describe("One summary per AI column of the list this page belongs to.").default([]), "next_cursor": z.union([z.string(), z.null()]).describe("The last id when more runs exist.").default(null), "runs": z.array(z.lazy(() => FillRunWireSchema)).describe("LIVE runs only. Named for what it holds rather than the house `items`, because this page carries a second collection (`columns`) and `items` beside it would name neither.") }).describe("LIVE runs plus the per-column summaries. Terminal runs do not\nride the poll: a finished run's story (its status, its error) lands\non the column summary the moment it leaves this list, so the page\ncarries the in-flight work and the summaries carry everything a\ncolumn needs to say about its past.");
export type FillRunPage = z.infer<typeof FillRunPageSchema>;

export const ListColumnSchema = z.discriminatedUnion("kind", [PlainColumnSchema, AiColumnSchema, WebhookColumnSchema]).describe("One column, exactly one kind: plain (hand-filled), ai (an agent's node fills it), or webhook (a Send webhook column). Narrow on `kind`.");
export type ListColumn = z.infer<typeof ListColumnSchema>;

export const ListSummarySchema = z.object({ "columns": z.array(z.lazy(() => ListColumnSchema)).describe("Display order.").default([]), "created_at": z.string(), "folder_id": z.string().describe("The containing folder; empty = loose at the root.").default(""), "id": z.string(), "label": z.string(), "origin": z.enum(["discover","csv","manual"]).describe("How the list came to exist."), "origin_ref": z.string().describe("e.g. the source run id for discover snapshots.").default(""), "row_count": z.number().int().describe("Total rows (the sheet may page far beyond one response)."), "updated_at": z.string() }).describe("One list as the index shows it (and the save-list response).");
export type ListSummary = z.infer<typeof ListSummarySchema>;

export const ListsPageSchema = z.object({ "items": z.array(z.lazy(() => ListSummarySchema)), "next_cursor": z.union([z.string(), z.null()]).describe("The last id when more lists exist.").default(null) });
export type ListsPage = z.infer<typeof ListsPageSchema>;

export const NodeRunWireSchema = z.object({ "created_at": z.string(), "heartbeat_at": z.string().describe("The run's latest state change; the client judges staleness against ROW_LEASE_STALE_SECONDS off the wire, warning-role only (never presented as failure)."), "id": z.string(), "result": z.union([z.lazy(() => CellRunResultSchema), z.null()]).describe("The run's stored result, served once it FINISHED with one (a cancel racing the last landing must not strand a paid diagnosis); None while the run is open, and for a run that ended without running (abandoned, or its config could not run).").default(null), "status": z.enum(["ready","queued","processing","deferred","done","abandoned","row_missing","list_missing"]) }).describe("One run, read by id (GET /v1/runs/{id}), and the echo of the\nbench's POST and cancel.");
export type NodeRunWire = z.infer<typeof NodeRunWireSchema>;

export const WebhookDeliveriesPageSchema = z.object({ "items": z.array(z.lazy(() => WebhookDeliveryWireSchema)), "next_cursor": z.union([z.string(), z.null()]).default(null) });
export type WebhookDeliveriesPage = z.infer<typeof WebhookDeliveriesPageSchema>;

export const WebhookDestinationCreatedSchema = z.object({ "destination": z.lazy(() => WebhookDestinationWireSchema), "signing_secret": z.string() }).describe("The create and rotate response: the ONE time a signing secret is\non the wire. It is minted server-side, stored encrypted, and never\nreturned again; a lost secret is replaced by rotating.");
export type WebhookDestinationCreated = z.infer<typeof WebhookDestinationCreatedSchema>;

export const WebhookDigestDataSchema = z.object({ "items": z.array(z.lazy(() => WebhookDigestItemSchema)).describe("The rows that completed, in the sheet's own order, top to bottom. The array is the only order: no item carries a row number."), "sheet": z.lazy(() => WebhookSheetRefSchema), "type": z.literal("digest").default("digest"), "waited_on": z.array(z.string()).describe("The columns whose settling makes a row complete; the keys each item's states report on.") }).describe("Rows that completed since the last delivery, for one sheet.");
export type WebhookDigestData = z.infer<typeof WebhookDigestDataSchema>;

export const WebhookEnvelopeDataSchema = z.discriminatedUnion("type", [WebhookPingDataSchema, WebhookDigestDataSchema]);
export type WebhookEnvelopeData = z.infer<typeof WebhookEnvelopeDataSchema>;

export const ImportResultSchema = z.object({ "list": z.lazy(() => ListSummarySchema), "rows": z.number().int().describe("Rows imported."), "skipped": z.number().int().describe("Blank lines and rows wider than the header, not imported.") }).describe("What a CSV upload produced.");
export type ImportResult = z.infer<typeof ImportResultSchema>;

export const WebhookEnvelopeSchema = z.object({ "data": z.lazy(() => WebhookEnvelopeDataSchema), "id": z.string(), "test": z.boolean().default(false), "timestamp": z.string(), "type": z.enum(["ping","digest"]), "version": z.number().int().default(1) }).describe("What a receiver gets, as the request body. Every delivery is a\nPOST of this JSON with three headers: `webhook-id` (this `id`),\n`webhook-timestamp` (unix seconds), and `webhook-signature`\n(`v1,` then base64 of HMAC-SHA256 over `\"{id}.{timestamp}.{body}\"`,\nkeyed by the base64-decoded secret after its `whsec_` prefix), the\nStandard Webhooks scheme.\n\n`type` says what `data` is. `test` says the delivery came from a\nTest button (a ping, or a sample digest sent from a sheet) and must\nnot be acted on as live data; a digest the schedule sends carries\nfalse. The top-level keys are reserved; everything a user defines\nis nested under `data`. A retried delivery carries a NEW id; a\ndigest's items each carry their own `event_id`, which is what a\nreceiver of batches deduplicates on.");
export type WebhookEnvelope = z.infer<typeof WebhookEnvelopeSchema>;

export const WebhookColumnPreviewResponseSchema = z.object({ "envelope": z.lazy(() => WebhookEnvelopeSchema) }).describe("The envelope a test send of these choices would carry, rendered by\nthe server and sent nowhere, so the sheet shows the truth before a\nsend rather than a reconstruction.");
export type WebhookColumnPreviewResponse = z.infer<typeof WebhookColumnPreviewResponseSchema>;

export const WebhookColumnTestResponseSchema = z.object({ "delivery": z.lazy(() => WebhookDeliveryWireSchema), "envelope": z.lazy(() => WebhookEnvelopeSchema) }).describe("A Send webhook column's test send: the delivery as recorded, and\nthe envelope exactly as the receiver got it, so the sheet can show\nthe body a test produced rather than reconstruct it.");
export type WebhookColumnTestResponse = z.infer<typeof WebhookColumnTestResponseSchema>;

export const WIRE_BOUNDS = {
  "AgentOutput": {
    "description": {
      "maxLength": 256
    },
    "key": {
      "maxLength": 40
    },
    "label": {
      "maxLength": 80
    }
  },
  "AiColumn": {
    "key": {
      "maxLength": 40
    },
    "label": {
      "maxLength": 80
    }
  },
  "PlainColumn": {
    "key": {
      "maxLength": 40
    },
    "label": {
      "maxLength": 80
    }
  },
  "WebhookColumn": {
    "key": {
      "maxLength": 40
    },
    "label": {
      "maxLength": 80
    }
  },
  "WebhookDeliveryWire": {
    "response_excerpt": {
      "maxLength": 1024
    }
  },
  "WebhookDestinationWire": {
    "label": {
      "maxLength": 128
    },
    "url": {
      "maxLength": 2048
    }
  },
  "AgentConfig": {
    "outputs": {
      "maxItems": 8,
      "minItems": 1
    },
    "prompt": {
      "maxLength": 262144
    }
  },
  "AgentListItem": {
    "label": {
      "maxLength": 128
    }
  },
  "AgentSummary": {
    "label": {
      "maxLength": 128
    }
  }
} as const;

export const RESERVED_OUTPUT_KEYS = [
  "construct",
  "copy",
  "dict",
  "from_orm",
  "json",
  "model_computed_fields",
  "model_config",
  "model_construct",
  "model_copy",
  "model_dump",
  "model_dump_json",
  "model_extra",
  "model_fields",
  "model_fields_set",
  "model_json_schema",
  "model_parametrized_name",
  "model_post_init",
  "model_rebuild",
  "model_validate",
  "model_validate_json",
  "model_validate_strings",
  "parse_file",
  "parse_obj",
  "parse_raw",
  "schema",
  "schema_json",
  "update_forward_refs",
  "validate"
] as const;

export const WIRE_CONSTANTS = {
  "DEFAULT_WEBHOOK_CADENCE_SECONDS": 900,
  "FREE_SEARCH_FILL_BUDGET": 768,
  "MAX_TOOL_CALLS": 6,
  "MAX_WEBHOOK_DESTINATIONS": 32,
  "MAX_WEBHOOK_HEADERS": 8,
  "NODE_RUN_ATTEMPTS": 4,
  "OPEN_NODE_RUN_STATES": [
    "ready",
    "queued",
    "processing",
    "deferred"
  ],
  "RESERVED_OUTPUT_MARKER": "_bwr_",
  "RESERVED_WEBHOOK_HEADER_NAMES": [
    "accept-encoding",
    "connection",
    "content-encoding",
    "content-length",
    "content-type",
    "host",
    "transfer-encoding",
    "user-agent",
    "webhook-id",
    "webhook-signature",
    "webhook-timestamp"
  ],
  "ROW_LEASE_STALE_SECONDS": 256,
  "SEARCH_PROVIDER_CHOICES": [
    "duckduckgo",
    "serper"
  ],
  "SETTLED_CELL_STATES": [
    "no_evidence",
    "no_answer",
    "unverified",
    "unparseable",
    "type_mismatch"
  ],
  "TEST_KEY_MAX_LENGTH": 64,
  "TEST_ROW_MAX_KEYS": 16,
  "TEST_VALUE_MAX_LENGTH": 512,
  "TOOL_STATUSES": {
    "find_contacts": [
      "open",
      "not_configured",
      "rate_limited",
      "unreachable",
      "error"
    ],
    "web_search": [
      "open",
      "not_configured",
      "rate_limited",
      "unreachable",
      "error"
    ]
  },
  "WEBHOOK_CADENCE_SECONDS": [
    300,
    900,
    3600,
    21600,
    86400
  ],
  "WEBHOOK_HEADER_NAME_GRAMMAR": "^[A-Za-z0-9-]+$",
  "WEBHOOK_HEADER_NAME_MAX_LENGTH": 128,
  "WEBHOOK_HEADER_VALUE_GRAMMAR": "^[\\x20-\\x7E\\t]*$",
  "WEBHOOK_HEADER_VALUE_MAX_LENGTH": 2048,
  "WEBHOOK_ID_HEADER": "webhook-id",
  "WEBHOOK_ROTATION_GRACE_SECONDS": 131072,
  "WEBHOOK_SECRET_PREFIX": "whsec_",
  "WEBHOOK_SIGNATURE_HEADER": "webhook-signature",
  "WEBHOOK_SIGNATURE_VERSION": "v1",
  "WEBHOOK_TIMESTAMP_HEADER": "webhook-timestamp"
} as const;
