# Generated by Django 6.1 on 2026-09-28 18:34
# State values are literals, not the app enums, because a migration that
# imports app code breaks a fresh migrate on the next rename.

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('state', models.CharField(default='pending', max_length=16, verbose_name='state')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='source')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='invited at')),
            ],
            options={
                'verbose_name': 'waitlist signup',
                'verbose_name_plural': 'waitlist signups',
                'indexes': [models.Index(fields=['state', 'id'], name='waitlist_state_idx')],
            },
        ),
    ]
