# Generated by Django 6.1 on 2026-09-20 13:38
# The jobs schema as one migration (the unreleased chain collapsed to its
# end state). State values are literals, not the app enums, because a
# migration that imports app code breaks a fresh migrate on the next rename.

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('kind', models.CharField(max_length=32, verbose_name='kind')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('progress', models.JSONField(default=dict, verbose_name='progress')),
                ('status', models.CharField(default='ready', max_length=16, verbose_name='status')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not before')),
                ('error', models.CharField(blank=True, default='', max_length=512, verbose_name='error')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='queued at')),
                ('processing_at', models.DateTimeField(blank=True, null=True, verbose_name='processing at')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='settled at')),
                ('last_state_change_at', models.DateTimeField(blank=True, null=True, verbose_name='last state change at')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'indexes': [models.Index(condition=models.Q(('status', 'ready')), fields=['status', 'id'], include=('not_before',), name='job_ready_idx'), models.Index(condition=models.Q(('status', 'processing')), fields=['status', 'last_state_change_at'], name='job_reclaim_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind', ''), _negated=True), name='job_kind_named')],
            },
        ),
    ]
