// Generate src/generated.ts (zod 4) from the shared contract artifact.
//
// The contract is emitted by the Python side (tools/schema_sync) into
// packages/openbower-schema/schema.json. This turns that one JSON Schema into
// named, cross-referencing zod schemas + inferred types, so the web validates
// API responses against the SAME definitions the server serializes. Never edit
// src/generated.ts by hand.
//
//   node scripts/generate.mjs          # write src/generated.ts
//   node scripts/generate.mjs --check  # exit non-zero if it's stale

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

// The contract lives in the OUTER monorepo (a Python workspace); this is a
// nested pnpm workspace, so resolve the repo root via git rather than counting
// ../ from this file (works from any cwd, survives the package moving).
const root = execSync("git rev-parse --show-toplevel").toString().trim();
const CONTRACT = join(root, "packages/openbower-schema/schema.json");
const OUTPUT = fileURLToPath(new URL("../src/generated.ts", import.meta.url));

if (!existsSync(CONTRACT)) {
  process.stderr.write(`Contract not found: ${CONTRACT}\nGenerate it first (tools/schema_sync).\n`);
  process.exit(1);
}

let doc;
try {
  doc = JSON.parse(readFileSync(CONTRACT, "utf8"));
} catch (err) {
  process.stderr.write(`Contract is not valid JSON: ${CONTRACT}\n${err.message}\n`);
  process.exit(1);
}

const defs = doc.$defs ?? {};
const names = Object.keys(defs);

// Collect the $defs each def references, for topological ordering.
function refsIn(node, acc = new Set()) {
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string") acc.add(node.$ref.split("/").pop());
    for (const v of Object.values(node)) refsIn(v, acc);
  }
  return acc;
}
const deps = Object.fromEntries(names.map((n) => [n, [...refsIn(defs[n])].filter((d) => d !== n && defs[d])]));

// Topological order (Kahn) so a const is declared before it's referenced.
const order = [];
const placed = new Set();
let progress = true;
while (order.length < names.length && progress) {
  progress = false;
  for (const n of names) {
    if (placed.has(n) || !deps[n].every((d) => placed.has(d))) continue;
    order.push(n);
    placed.add(n);
    progress = true;
  }
}
const cyclic = names.filter((n) => !placed.has(n));
order.push(...cyclic);

const constName = (node) => `${node.$ref.split("/").pop()}Schema`;

// Node overrides json-schema-to-zod calls before its own parsing:
// (1) a $ref always becomes z.lazy(() => XSchema). Lazy unconditionally, not
//     only when a mutual cycle is detected: a SELF-referential model
//     (X -> X) is topologically placed (its self-edge is filtered from deps),
//     so a non-lazy `XSchema` reference inside its own initializer would be a
//     TDZ ReferenceError at import. Lazy is also correct for plain forward
//     refs, so this is always safe.
// (2) a date-time string becomes zod 4's z.iso.datetime (matching the server's
//     tz-aware ISO output).
const parserOverride = (schema) => {
  if (schema && typeof schema.$ref === "string") {
    return `z.lazy(() => ${constName(schema)})`;
  }
  if (schema?.type === "string" && schema.format === "date-time") {
    return "z.iso.datetime({ offset: true })";
  }
};

const banner = "// Generated by packages/schema/scripts/generate.mjs from the shared\n// contract (packages/openbower-schema/schema.json). Do not edit by hand.\n";
const body = order
  .map((name) => {
    // jsonSchemaToZod already appends .describe(...) from the def's description.
    const zod = jsonSchemaToZod(defs[name], { module: "none", type: false, parserOverride });
    return `export const ${name}Schema = ${zod};\nexport type ${name} = z.infer<typeof ${name}Schema>;`;
  })
  .join("\n\n");
const rendered = `${banner}\nimport { z } from "zod";\n\n${body}\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== rendered.replace(/\r\n/g, "\n")) {
    process.stderr.write("src/generated.ts is stale; run `pnpm --filter @bower/schema generate`.\n");
    process.exit(1);
  }
} else {
  writeFileSync(OUTPUT, rendered);
  process.stdout.write(`Wrote ${OUTPUT}\n`);
}
