// Generate src/generated.ts (zod 4) from the shared contract artifact.
//
// The contract is emitted by the Python side (tools/schema_sync) into
// packages/openbower-schema/schema.json. This turns that one JSON Schema into
// named, cross-referencing zod schemas + inferred types, so the web validates
// API responses against the SAME definitions the server serializes. Never edit
// src/generated.ts by hand.
//
//   node scripts/generate.mjs          # write src/generated.ts
//   node scripts/generate.mjs --check  # exit non-zero if it's stale

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

// The contract lives in the OUTER monorepo (a Python workspace); this is a
// nested pnpm workspace, so resolve the repo root via git rather than counting
// ../ from this file (works from any cwd, survives the package moving).
const root = execSync("git rev-parse --show-toplevel").toString().trim();
const CONTRACT = join(root, "packages/openbower-schema/schema.json");
const OUTPUT = fileURLToPath(new URL("../src/generated.ts", import.meta.url));

if (!existsSync(CONTRACT)) {
  process.stderr.write(`Contract not found: ${CONTRACT}\nGenerate it first (tools/schema_sync).\n`);
  process.exit(1);
}

let doc;
try {
  doc = JSON.parse(readFileSync(CONTRACT, "utf8"));
} catch (err) {
  process.stderr.write(`Contract is not valid JSON: ${CONTRACT}\n${err.message}\n`);
  process.exit(1);
}

const defs = doc.$defs ?? {};
const names = Object.keys(defs);

// Collect the $defs each def references, for topological ordering.
function refsIn(node, acc = new Set()) {
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string") acc.add(node.$ref.split("/").pop());
    for (const v of Object.values(node)) refsIn(v, acc);
  }
  return acc;
}
const deps = Object.fromEntries(names.map((n) => [n, [...refsIn(defs[n])].filter((d) => d !== n && defs[d])]));

// Topological order (Kahn) so a const is declared before it's referenced.
const order = [];
const placed = new Set();
let progress = true;
while (order.length < names.length && progress) {
  progress = false;
  for (const n of names) {
    if (placed.has(n) || !deps[n].every((d) => placed.has(d))) continue;
    order.push(n);
    placed.add(n);
    progress = true;
  }
}
const cyclic = names.filter((n) => !placed.has(n));
order.push(...cyclic);

const constName = (node) => `${node.$ref.split("/").pop()}Schema`;

// Node overrides json-schema-to-zod calls before its own parsing:
// (1) a $ref always becomes z.lazy(() => XSchema). Lazy unconditionally, not
//     only when a mutual cycle is detected: a SELF-referential model
//     (X -> X) is topologically placed (its self-edge is filtered from deps),
//     so a non-lazy `XSchema` reference inside its own initializer would be a
//     TDZ ReferenceError at import. Lazy is also correct for plain forward
//     refs, so this is always safe.
// (2) a date-time string becomes zod 4's z.iso.datetime (matching the server's
//     tz-aware ISO output).
const parserOverride = (schema) => {
  if (schema && typeof schema.$ref === "string") {
    return `z.lazy(() => ${constName(schema)})`;
  }
  // (3) a discriminated union (pydantic emits oneOf + discriminator)
  //     becomes a plain z.union of its members: the library's own oneOf
  //     rendering is an untyped refinement (z.any), which would erase
  //     the inferred type every consumer narrows on.
  if (Array.isArray(schema?.oneOf) && schema.discriminator) {
    return `z.union([${schema.oneOf.map((member) => parserOverride(member) ?? jsonSchemaToZod(member, { module: "none", type: false, parserOverride })).join(", ")}])`;
  }
  if (schema?.type === "string" && schema.format === "date-time") {
    return "z.iso.datetime({ offset: true })";
  }
};

const banner = "// Generated by packages/schema/scripts/generate.mjs from the shared\n// contract (packages/openbower-schema/schema.json). Do not edit by hand.\n";
const body = order
  .map((name) => {
    // jsonSchemaToZod already appends .describe(...) from the def's description.
    const zod = jsonSchemaToZod(defs[name], { module: "none", type: false, parserOverride });
    return `export const ${name}Schema = ${zod};\nexport type ${name} = z.infer<typeof ${name}Schema>;`;
  })
  .join("\n\n");
// The contract's size bounds, mechanically projected (maxLength on
// strings, maxItems/minItems on arrays) so client-side enforcement
// (input maxLength, row caps) reads the SAME numbers the server
// validates with instead of hand-copying them.
const bounds = {};
// A nullable/optional field wraps its constraints in anyOf members;
// the projection must look inside or those bounds silently vanish.
function boundIn(node, key) {
  if (typeof node?.[key] === "number") return node[key];
  for (const member of node?.anyOf ?? []) {
    if (typeof member?.[key] === "number") return member[key];
  }
  return undefined;
}
for (const name of order) {
  const props = defs[name]?.properties ?? {};
  for (const [prop, node] of Object.entries(props)) {
    const entry = {};
    for (const key of ["maxLength", "maxItems", "minItems"]) {
      const value = boundIn(node, key);
      if (value !== undefined) entry[key] = value;
    }
    if (Object.keys(entry).length > 0) (bounds[name] ??= {})[prop] = entry;
  }
}
const boundsBody = `export const WIRE_BOUNDS = ${JSON.stringify(bounds, null, 2)} as const;`;
// Server-refused output keys and scalar wire facts, straight off the
// contract document (see tools/schema_sync/generate.py). A missing
// extension REFUSES like a missing contract file: `?? []` would emit
// an empty reserved set that typechecks, passes --check, and silently
// disarms the readiness mirror it exists to arm.
if (!Array.isArray(doc["x-reserved-output-keys"]) || doc["x-reserved-output-keys"].length === 0) {
  process.stderr.write("Contract is missing x-reserved-output-keys; regenerate it (tools/schema_sync).\n");
  process.exit(1);
}
if (typeof doc["x-constants"]?.TEST_ROW_MAX_KEYS !== "number") {
  // Symmetric with the reserved-keys guard: shape-checked, not just
  // present (an empty object would disarm the bench's row-cap copy).
  process.stderr.write("Contract is missing x-constants.TEST_ROW_MAX_KEYS; regenerate it (tools/schema_sync).\n");
  process.exit(1);
}
const reservedBody = `export const RESERVED_OUTPUT_KEYS = ${JSON.stringify(doc["x-reserved-output-keys"], null, 2)} as const;`;
const constantsBody = `export const WIRE_CONSTANTS = ${JSON.stringify(doc["x-constants"], null, 2)} as const;`;

const rendered = `${banner}\nimport { z } from "zod";\n\n${body}\n\n${boundsBody}\n\n${reservedBody}\n\n${constantsBody}\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== rendered.replace(/\r\n/g, "\n")) {
    process.stderr.write("src/generated.ts is stale; run `pnpm --filter @bower/schema generate`.\n");
    process.exit(1);
  }
} else {
  writeFileSync(OUTPUT, rendered);
  process.stdout.write(`Wrote ${OUTPUT}\n`);
}
