# Generated by Django 6.1 on 2026-09-16 16:59
# The webhooks schema as one migration (the unreleased chain collapsed to
# its end state). State values are literals, not the app enums, because a
# migration that imports app code breaks a fresh migrate on the next rename.

import auth_client.fields
import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('destination_id', models.CharField(max_length=26, verbose_name='destination id')),
                ('kind', models.CharField(max_length=16, verbose_name='kind')),
                ('status', models.CharField(max_length=16, verbose_name='status')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='http status')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='duration ms')),
                ('error', models.CharField(blank=True, default='', max_length=256, verbose_name='error')),
                ('response_excerpt', models.CharField(blank=True, default='', max_length=1024, verbose_name='response excerpt')),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'indexes': [models.Index(fields=['destination_id', 'id'], name='webhook_delivery_dest_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDestination',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('label', models.CharField(max_length=128, verbose_name='label')),
                ('url', models.CharField(max_length=2048, verbose_name='url')),
                ('headers', auth_client.fields.EncryptedTextField(blank=True, default='{}', verbose_name='headers')),
                ('signing_secret', auth_client.fields.EncryptedTextField(verbose_name='signing secret')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'webhook destination',
                'verbose_name_plural': 'webhook destinations',
                'indexes': [models.Index(fields=['account_id', 'id'], name='webhook_dest_account_idx')],
            },
        ),
    ]
