# Generated by Django 6.1 on 2026-09-20 16:58
# The lists schema as one migration (the unreleased chain collapsed to its
# end state). State values are literals, not the app enums, because a
# migration that imports app code breaks a fresh migrate on the next rename.
# `columns` is a plain jsonb here; the model reads it through
# lists.fields.ListColumnsField, which deconstructs as JSONField so this
# file never imports the contract package.


import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
                'indexes': [models.Index(fields=['account_id', 'id'], name='folder_account_idx')],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('folder_id', models.CharField(blank=True, default='', max_length=26, verbose_name='folder id')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('columns', models.JSONField(default=list, help_text="The contract's ListColumn dumps, in display order", verbose_name='columns')),
                ('origin', models.CharField(help_text='ListOrigin', max_length=16, verbose_name='origin')),
                ('origin_ref', models.CharField(blank=True, default='', help_text='e.g. the source run id', max_length=64, verbose_name='origin ref')),
                ('row_count', models.IntegerField(default=0, verbose_name='row count')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'indexes': [models.Index(fields=['account_id', 'id'], name='list_account_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListCellState',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('row_id', models.CharField(max_length=26, verbose_name='row id')),
                ('column_key', models.CharField(max_length=40, verbose_name='column key')),
                ('state', models.CharField(default='no_evidence', max_length=32, verbose_name='state')),
                ('source', models.CharField(default='fill', max_length=8, verbose_name='source')),
                ('fill_run_id', models.CharField(blank=True, max_length=26, null=True, verbose_name='fill run id')),
                ('tools', models.JSONField(blank=True, default=dict, verbose_name='tool statuses')),
            ],
            options={
                'verbose_name': 'list cell state',
                'verbose_name_plural': 'list cell states',
                'indexes': [models.Index(fields=['list_id', 'column_key', 'state'], name='cell_state_column_idx'), models.Index(fields=['list_id', 'state'], name='cell_state_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('list_id', 'row_id', 'column_key'), name='cell_state_cell_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ListRow',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('position', models.IntegerField(help_text='1-based, dense; the display/paging order', verbose_name='position')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
            ],
            options={
                'verbose_name': 'list row',
                'verbose_name_plural': 'list rows',
                'constraints': [models.UniqueConstraint(fields=('list_id', 'position'), name='list_row_position_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('workflow_id', models.CharField(blank=True, default='', max_length=26, verbose_name='workflow id')),
                ('path_id', models.CharField(blank=True, default='', max_length=26, verbose_name='path id')),
                ('kind', models.CharField(max_length=32, verbose_name='kind')),
                ('config', models.JSONField(default=dict, verbose_name='config')),
                ('identity', models.CharField(blank=True, default='', max_length=64, verbose_name='identity')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
            ],
            options={
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
                'indexes': [models.Index(fields=['account_id', 'kind'], name='node_account_kind_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('identity', ''), _negated=True), fields=('account_id', 'workflow_id', 'kind', 'identity'), name='node_identity_uniq'), models.UniqueConstraint(condition=models.Q(('path_id', ''), _negated=True), fields=('path_id', 'rank'), name='node_path_rank_uniq')],
            },
        ),
        migrations.CreateModel(
            name='NodePath',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('workflow_id', models.CharField(max_length=26, verbose_name='workflow id')),
            ],
            options={
                'verbose_name': 'node path',
                'verbose_name_plural': 'node paths',
                'indexes': [models.Index(fields=['account_id', 'workflow_id'], name='node_path_workflow_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('fill_run_id', models.CharField(blank=True, max_length=26, null=True, verbose_name='fill run id')),
                ('row_id', models.CharField(blank=True, max_length=26, null=True, verbose_name='row id')),
                ('list_id', models.CharField(blank=True, default='', max_length=26, verbose_name='list id')),
                ('input', models.JSONField(default=dict, verbose_name='input')),
                ('started_by', models.CharField(blank=True, default='', max_length=26, verbose_name='started by')),
                ('node_id', models.CharField(max_length=26, verbose_name='node id')),
                ('kind', models.CharField(max_length=32, verbose_name='kind')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('status', models.CharField(default='queued', max_length=16, verbose_name='status')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not before')),
                ('parked', models.BooleanField(default=False, verbose_name='parked')),
                ('leased_by', models.CharField(blank=True, default='', max_length=128, verbose_name='leased by')),
                ('result', models.JSONField(default=dict, verbose_name='result')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='queued at')),
                ('processing_at', models.DateTimeField(blank=True, null=True, verbose_name='processing at')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='settled at')),
                ('last_state_change_at', models.DateTimeField(blank=True, null=True, verbose_name='last state change at')),
            ],
            options={
                'verbose_name': 'node run',
                'verbose_name_plural': 'node runs',
                'indexes': [models.Index(condition=models.Q(('fill_run_id__isnull', False)), fields=['status', 'fill_run_id', 'position', 'id'], include=('not_before',), name='node_run_fill_idx'), models.Index(condition=models.Q(('fill_run_id__isnull', True)), fields=['status', 'list_id', 'position', 'id'], include=('not_before', 'kind'), name='node_run_autofill_idx'), models.Index(condition=models.Q(('kind', 'webhook')), fields=['node_id', 'status', 'not_before', 'position', 'id'], name='node_run_webhook_due_idx'), models.Index(condition=models.Q(('kind', 'webhook')), fields=['row_id', 'node_id', '-id'], name='node_run_webhook_cell_idx'), models.Index(condition=models.Q(('status__in', ('ready', 'queued', 'processing', 'deferred'))), fields=['status', 'last_state_change_at'], name='node_run_reclaim_idx')],
                'constraints': [models.UniqueConstraint(fields=('fill_run_id', 'row_id'), name='node_run_fill_row_uniq'), models.UniqueConstraint(condition=models.Q(('fill_run_id__isnull', True), ('status__in', ('ready', 'queued', 'processing', 'deferred'))), fields=('row_id', 'node_id'), name='node_run_open_uniq'), models.CheckConstraint(condition=models.Q(('kind', ''), _negated=True), name='node_run_kind_named')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedIngestEvent',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('event_id', models.CharField(max_length=255, verbose_name='event id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
            ],
            options={
                'verbose_name': 'processed ingest event',
                'verbose_name_plural': 'processed ingest events',
                'constraints': [models.UniqueConstraint(fields=('account_id', 'event_id'), name='uniq_processed_ingest_account_event')],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflows',
                'constraints': [models.UniqueConstraint(fields=('list_id',), name='workflow_list_uniq')],
            },
        ),
    ]
