# Generated by Django 6.1 on 2026-08-18 00:50

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
                'indexes': [models.Index(fields=['account_id', 'id'], name='folder_account_idx')],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('folder_id', models.CharField(blank=True, default='', max_length=26, verbose_name='folder id')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('columns', models.JSONField(default=list, help_text='[{key, label, type}] in display order', verbose_name='columns')),
                ('origin', models.CharField(help_text='ListOrigin', max_length=16, verbose_name='origin')),
                ('origin_ref', models.CharField(blank=True, default='', help_text='e.g. the source run id', max_length=64, verbose_name='origin ref')),
                ('row_count', models.IntegerField(default=0, verbose_name='row count')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'indexes': [models.Index(fields=['account_id', 'id'], name='list_account_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListRow',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('position', models.IntegerField(help_text='1-based, dense; the display/paging order', verbose_name='position')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
            ],
            options={
                'verbose_name': 'list row',
                'verbose_name_plural': 'list rows',
                'constraints': [models.UniqueConstraint(fields=('list_id', 'position'), name='list_row_position_uniq')],
            },
        ),
    ]
