# Generated by Django 6.1 on 2026-08-25 16:58

import lists.constants
import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('agent_id', models.CharField(max_length=26, verbose_name='agent id')),
                ('status', models.CharField(default=lists.constants.FillStatus['PENDING'], max_length=16, verbose_name='status')),
                ('column_keys', models.JSONField(default=list, verbose_name='column keys')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='config snapshot')),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='config fingerprint')),
                ('concurrency', models.IntegerField(default=0, verbose_name='concurrency')),
                ('confirmed_row_count', models.IntegerField(verbose_name='confirmed row count')),
                ('attempted', models.IntegerField(default=0, verbose_name='attempted')),
                ('filled', models.IntegerField(default=0, verbose_name='filled')),
                ('blank', models.IntegerField(default=0, verbose_name='blank')),
                ('transient', models.IntegerField(default=0, verbose_name='transient')),
                ('row_seconds', models.IntegerField(default=0, verbose_name='row seconds')),
                ('search_wait_seconds', models.IntegerField(default=0, verbose_name='search wait seconds')),
                ('concurrency_point', models.IntegerField(default=0, verbose_name='concurrency point')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='heartbeat at')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='error code')),
                ('error_message', models.CharField(blank=True, default='', max_length=256, verbose_name='error message')),
            ],
            options={
                'verbose_name': 'fill',
                'verbose_name_plural': 'fills',
                'indexes': [models.Index(fields=['account_id', 'id'], name='fill_account_idx'), models.Index(fields=['list_id', '-id'], name='fill_list_recent_idx'), models.Index(condition=models.Q(('status__in', (lists.constants.FillStatus['PENDING'], lists.constants.FillStatus['RUNNING']))), fields=['id'], name='fill_live_idx')],
            },
        ),
        migrations.CreateModel(
            name='FillCellState',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('row_id', models.CharField(max_length=26, verbose_name='row id')),
                ('column_key', models.CharField(max_length=40, verbose_name='column key')),
                ('state', models.CharField(default=lists.constants.StoredCellState['NO_EVIDENCE'], max_length=16, verbose_name='state')),
                ('fill_id', models.CharField(max_length=26, verbose_name='fill id')),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='config fingerprint')),
            ],
            options={
                'verbose_name': 'fill cell state',
                'verbose_name_plural': 'fill cell states',
                'indexes': [models.Index(fields=['list_id', 'column_key', 'state'], name='cell_state_column_idx'), models.Index(fields=['list_id', 'state'], name='cell_state_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('list_id', 'row_id', 'column_key'), name='cell_state_cell_uniq')],
            },
        ),
        migrations.CreateModel(
            name='FillTask',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('fill_id', models.CharField(max_length=26, verbose_name='fill id')),
                ('row_id', models.CharField(max_length=26, verbose_name='row id')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('status', models.CharField(default=lists.constants.FillTaskStatus['QUEUED'], max_length=16, verbose_name='status')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not before')),
                ('parked', models.BooleanField(default=False, verbose_name='parked')),
                ('leased_at', models.DateTimeField(blank=True, null=True, verbose_name='leased at')),
                ('leased_by', models.CharField(blank=True, default='', max_length=128, verbose_name='leased by')),
                ('result', models.JSONField(default=dict, verbose_name='result')),
            ],
            options={
                'verbose_name': 'fill task',
                'verbose_name_plural': 'fill tasks',
                'indexes': [models.Index(condition=models.Q(('status', lists.constants.FillTaskStatus['QUEUED'])), fields=['fill_id', 'position'], name='fill_task_claim_idx')],
                'constraints': [models.UniqueConstraint(fields=('fill_id', 'row_id'), name='fill_task_fill_row_uniq')],
            },
        ),
    ]
