# Generated by Django 6.1 on 2026-09-15 17:50
# The collapsed lists schema: 0002-0013 folded into the end state. State
# values are literals, not the app enums, because a migration that imports
# app code breaks a fresh migrate on the next rename.

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('kind', models.CharField(default='normal', max_length=8, verbose_name='kind')),
                ('list_id', models.CharField(blank=True, default='', max_length=26, verbose_name='list id')),
                ('agent_id', models.CharField(blank=True, default='', max_length=26, verbose_name='agent id')),
                ('row_data', models.JSONField(default=list, verbose_name='row data')),
                ('status', models.CharField(default='pending', max_length=16, verbose_name='status')),
                ('column_keys', models.JSONField(default=list, verbose_name='column keys')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='config snapshot')),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='config fingerprint')),
                ('confirmed_row_count', models.IntegerField(verbose_name='confirmed row count')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='error code')),
                ('error_message', models.CharField(blank=True, default='', max_length=256, verbose_name='error message')),
            ],
            options={
                'verbose_name': 'fill',
                'verbose_name_plural': 'fills',
                'indexes': [models.Index(fields=['account_id', 'id'], name='fill_account_idx'), models.Index(fields=['list_id', '-id'], name='fill_list_recent_idx'), models.Index(condition=models.Q(('status__in', ('pending', 'running'))), fields=['id'], name='fill_live_idx'), models.Index(fields=['account_id', 'kind'], name='fill_account_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListCellState',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('row_id', models.CharField(max_length=26, verbose_name='row id')),
                ('column_key', models.CharField(max_length=40, verbose_name='column key')),
                ('state', models.CharField(default='no_evidence', max_length=32, verbose_name='state')),
                ('fill_run_id', models.CharField(blank=True, max_length=26, null=True, verbose_name='fill run id')),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='config fingerprint')),
                ('tools', models.JSONField(blank=True, default=dict, verbose_name='tool statuses')),
            ],
            options={
                'verbose_name': 'list cell state',
                'verbose_name_plural': 'list cell states',
                'indexes': [models.Index(fields=['list_id', 'column_key', 'state'], name='cell_state_column_idx'), models.Index(fields=['list_id', 'state'], name='cell_state_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('list_id', 'row_id', 'column_key'), name='cell_state_cell_uniq')],
            },
        ),
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('fill_run_id', models.CharField(blank=True, max_length=26, null=True, verbose_name='fill run id')),
                ('row_id', models.CharField(max_length=26, verbose_name='row id')),
                ('list_id', models.CharField(blank=True, default='', max_length=26, verbose_name='list id')),
                ('agent_id', models.CharField(blank=True, max_length=26, null=True, verbose_name='agent id')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('status', models.CharField(default='queued', max_length=16, verbose_name='status')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not before')),
                ('parked', models.BooleanField(default=False, verbose_name='parked')),
                ('leased_by', models.CharField(blank=True, default='', max_length=128, verbose_name='leased by')),
                ('result', models.JSONField(default=dict, verbose_name='result')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='queued at')),
                ('processing_at', models.DateTimeField(blank=True, null=True, verbose_name='processing at')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='settled at')),
                ('last_state_change_at', models.DateTimeField(blank=True, null=True, verbose_name='last state change at')),
            ],
            options={
                'verbose_name': 'node run',
                'verbose_name_plural': 'node runs',
                'indexes': [models.Index(condition=models.Q(('fill_run_id__isnull', False)), fields=['status', 'fill_run_id', 'position', 'id'], include=('not_before',), name='node_run_fill_idx'), models.Index(condition=models.Q(('fill_run_id__isnull', True)), fields=['status', 'list_id', 'position', 'id'], include=('not_before',), name='node_run_autofill_idx'), models.Index(condition=models.Q(('status__in', ('ready', 'queued', 'processing'))), fields=['status', 'last_state_change_at'], name='node_run_reclaim_idx')],
                'constraints': [models.UniqueConstraint(fields=('fill_run_id', 'row_id'), name='node_run_fill_row_uniq'), models.UniqueConstraint(condition=models.Q(('fill_run_id__isnull', True)), fields=('row_id', 'agent_id'), name='node_run_autofill_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedIngestEvent',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('event_id', models.CharField(max_length=255, verbose_name='event id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
            ],
            options={
                'verbose_name': 'processed ingest event',
                'verbose_name_plural': 'processed ingest events',
                'constraints': [models.UniqueConstraint(fields=('account_id', 'event_id'), name='uniq_processed_ingest_account_event')],
            },
        ),
    ]
