# Generated by Django 6.1 on 2026-08-28 17:25

import lists.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_fill_fillcellstate_filltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillcellstate',
            name='state',
            field=models.CharField(default=lists.constants.StoredCellState['NO_EVIDENCE'], max_length=32, verbose_name='state'),
        ),
    ]
