# Generated by Django 6.1 on 2026-08-28 20:10

import lists.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_fill_fillcellstate_filltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillcellstate',
            name='tools',
            field=models.JSONField(blank=True, default=dict, verbose_name='tool statuses'),
        ),
        migrations.AlterField(
            model_name='fillcellstate',
            name='state',
            field=models.CharField(default=lists.constants.StoredCellState['NO_EVIDENCE'], max_length=32, verbose_name='state'),
        ),
    ]
