# Generated by Django 6.1 on 2026-09-03 18:05

import lists.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_cell_state_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='kind',
            field=models.CharField(default=lists.constants.FillKind['NORMAL'], max_length=8, verbose_name='kind'),
        ),
        migrations.AddField(
            model_name='fill',
            name='row_data',
            field=models.JSONField(default=list, verbose_name='row data'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='agent_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='agent id'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='list_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='list id'),
        ),
        migrations.AddIndex(
            model_name='fill',
            index=models.Index(fields=['account_id', 'kind'], name='fill_account_kind_idx'),
        ),
    ]
