# Generated by Django 6.1 on 2026-09-09 22:30

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_fill_kind_row_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedIngestEvent',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('event_id', models.CharField(max_length=255, verbose_name='event id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
            ],
            options={
                'verbose_name': 'processed ingest event',
                'verbose_name_plural': 'processed ingest events',
                'constraints': [models.UniqueConstraint(fields=('account_id', 'event_id'), name='uniq_processed_ingest_account_event')],
            },
        ),
    ]
