# Generated by Django 6.1 on 2026-09-10 00:29

import openbower_kernel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_processedingestevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutofillTask',
            fields=[
                ('id', openbower_kernel.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('list_id', models.CharField(max_length=26, verbose_name='list id')),
                ('row_id', models.CharField(max_length=26, verbose_name='row id')),
            ],
            options={
                'verbose_name': 'autofill task',
                'verbose_name_plural': 'autofill tasks',
            },
        ),
    ]
