# Generated by Django 6.1 on 2026-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_rename_fill_id_fill_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filltask',
            name='agent_id',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='agent id'),
        ),
        migrations.AlterField(
            model_name='fillcellstate',
            name='fill_run_id',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='fill run id'),
        ),
        migrations.AlterField(
            model_name='filltask',
            name='fill_run_id',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='fill run id'),
        ),
        migrations.AddConstraint(
            model_name='filltask',
            constraint=models.UniqueConstraint(condition=models.Q(('fill_run_id__isnull', True)), fields=('row_id', 'agent_id'), name='fill_task_autofill_uniq'),
        ),
    ]
