# Generated by Django 6.1 on 2026-09-10 16:56

import lists.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_filltask_agent_id_alter_fillcellstate_fill_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filltask',
            name='last_state_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last state change at'),
        ),
        migrations.AddField(
            model_name='filltask',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing at'),
        ),
        migrations.AddField(
            model_name='filltask',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='queued at'),
        ),
        migrations.AddField(
            model_name='filltask',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='settled at'),
        ),
        migrations.AddIndex(
            model_name='filltask',
            index=models.Index(condition=models.Q(('status__in', (lists.constants.FillTaskStatus['READY'], lists.constants.FillTaskStatus['QUEUED'], lists.constants.FillTaskStatus['PROCESSING']))), fields=['status', 'last_state_change_at'], name='fill_task_reclaim_idx'),
        ),
    ]
