# Generated by Django 6.1 on 2026-09-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_filltask_last_state_change_at_filltask_processing_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='attempted',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='concurrency_point',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='heartbeat_at',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='row_seconds',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='search_wait_seconds',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='transient',
        ),
    ]
