# Generated by Django 6.1 on 2026-09-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_remove_fill_attempted_remove_fill_blank_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filltask',
            name='fill_task_claim_idx',
        ),
    ]
