# Generated by Django 6.1 on 2026-09-10 20:15

from django.db import migrations, models


def backfill_list_id(apps, schema_editor):
    # Denormalize each existing task's list: a fill-backed task reads it
    # off its Fill, an autofill task off its row's ListRow. A TEST fill's
    # list_id is "" by construction, so its tasks stay blank. Streamed in
    # bounded chunks (never the whole table in memory), and each chunk
    # fetches only the fills/rows it references, so a fresh deploy (no
    # tasks yet) touches nothing.
    FillTask = apps.get_model("lists", "FillTask")
    Fill = apps.get_model("lists", "Fill")
    ListRow = apps.get_model("lists", "ListRow")
    CHUNK = 500

    def flush(tasks):
        fill_ids = {str(t.fill_run_id) for t in tasks if t.fill_run_id}
        row_ids = {t.row_id for t in tasks if not t.fill_run_id}
        fills = {str(f.id): f.list_id for f in Fill.objects.filter(id__in=fill_ids).only("id", "list_id")}
        rows = {str(r.id): r.list_id for r in ListRow.objects.filter(id__in=row_ids).only("id", "list_id")}
        updates = []
        for t in tasks:
            lid = fills.get(str(t.fill_run_id), "") if t.fill_run_id else rows.get(t.row_id, "")
            if lid and lid != t.list_id:
                t.list_id = lid
                updates.append(t)
        if updates:
            FillTask.objects.bulk_update(updates, ["list_id"], batch_size=CHUNK)

    chunk = []
    for t in FillTask.objects.all().only("id", "fill_run_id", "row_id", "list_id").iterator(chunk_size=CHUNK):
        chunk.append(t)
        if len(chunk) >= CHUNK:
            flush(chunk)
            chunk = []
    flush(chunk)


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_remove_filltask_fill_task_claim_idx_and_more'),
    ]

    operations = [
        # A CharField default is NOT NULL at the DB, and Django drops that
        # default after adding the column, so old code still inserting a
        # FillTask without list_id would violate NOT NULL. This is a
        # STOP-THE-WORLD deploy (compose recreates every container at once),
        # so no pre-list_id writer overlaps it; a rolling deploy would need
        # the three-step (add nullable, backfill, set NOT NULL) instead.
        migrations.AddField(
            model_name='filltask',
            name='list_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='list id'),
        ),
        migrations.RunPython(backfill_list_id, migrations.RunPython.noop),
        # Two lane-split partial indexes: IS NULL cannot give the autofill
        # firehose an ordering pathkey, so the null-run lane needs its own
        # partial index (with list_id, for per-list seeks) and the
        # fill-backed lane keeps its equality seek. The list_id column above
        # must exist first for the autofill index.
        migrations.AddIndex(
            model_name='filltask',
            index=models.Index(
                fields=['status', 'fill_run_id', 'position', 'id'],
                include=('not_before',),
                condition=models.Q(('fill_run_id__isnull', False)),
                name='fill_task_fill_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='filltask',
            index=models.Index(
                fields=['status', 'list_id', 'position', 'id'],
                include=('not_before',),
                condition=models.Q(('fill_run_id__isnull', True)),
                name='fill_task_autofill_idx',
            ),
        ),
    ]
