# Generated by Django 6.1 on 2026-09-10 20:15

from django.db import migrations, models


def backfill_list_id(apps, schema_editor):
    # Denormalize each existing task's list: a fill-backed task reads it
    # off its Fill, an autofill task off its row's ListRow. A TEST fill's
    # list_id is "" by construction, so its tasks stay blank. Fetches only
    # the fills/rows the tasks actually reference, so a fresh deploy (no
    # tasks yet) touches nothing.
    FillTask = apps.get_model("lists", "FillTask")
    Fill = apps.get_model("lists", "Fill")
    ListRow = apps.get_model("lists", "ListRow")
    tasks = list(FillTask.objects.all().only("id", "fill_run_id", "row_id", "list_id"))
    if not tasks:
        return
    fill_ids = {str(t.fill_run_id) for t in tasks if t.fill_run_id}
    row_ids = {t.row_id for t in tasks if not t.fill_run_id}
    fills = {str(f.id): f.list_id for f in Fill.objects.filter(id__in=fill_ids).only("id", "list_id")}
    rows = {str(r.id): r.list_id for r in ListRow.objects.filter(id__in=row_ids).only("id", "list_id")}
    updates = []
    for t in tasks:
        lid = fills.get(str(t.fill_run_id), "") if t.fill_run_id else rows.get(t.row_id, "")
        if lid and lid != t.list_id:
            t.list_id = lid
            updates.append(t)
    if updates:
        FillTask.objects.bulk_update(updates, ["list_id"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_remove_filltask_fill_task_claim_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filltask',
            name='list_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='list id'),
        ),
        migrations.RunPython(backfill_list_id, migrations.RunPython.noop),
        # Split the single provisioner index (0010) by lane: IS NULL cannot
        # give the autofill firehose an ordering pathkey, so the null-run
        # lane needs its own partial index (with list_id, for per-list
        # seeks) and the fill-backed lane keeps its equality seek. The
        # list_id column above must exist first for the autofill index.
        migrations.RemoveIndex(model_name='filltask', name='fill_task_provision_idx'),
        migrations.AddIndex(
            model_name='filltask',
            index=models.Index(
                fields=['status', 'fill_run_id', 'position', 'id'],
                include=('not_before',),
                condition=models.Q(('fill_run_id__isnull', False)),
                name='fill_task_fill_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='filltask',
            index=models.Index(
                fields=['status', 'list_id', 'position', 'id'],
                include=('not_before',),
                condition=models.Q(('fill_run_id__isnull', True)),
                name='fill_task_autofill_idx',
            ),
        ),
    ]
