# Generated by Django 6.1 on 2026-09-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_filltask_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filltask',
            name='leased_at',
        ),
    ]
