# Generated by Django 6.1 on 2026-09-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_remove_filltask_leased_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='concurrency',
        ),
    ]
